-- Every column the squad client expects, checked against Postgres.
-- Rows returned = columns the client reads/writes that Postgres does not have.
-- Each one is a potential PGRST204 that blocks the whole FIFO upload queue.
with expected(tbl, col) as (values
  ('profiles','id'),
  ('profiles','username'),
  ('profiles','display_name'),
  ('profiles','avatar_url'),
  ('profiles','bodyweight_kg'),
  ('profiles','calorie_tracking_enabled'),
  ('profiles','duration_tracking_enabled'),
  ('profiles','sex'),
  ('profiles','created_at'),
  ('exercises','id'),
  ('exercises','user_id'),
  ('exercises','name'),
  ('exercises','categories'),
  ('exercises','equipment'),
  ('exercises','is_bodyweight'),
  ('exercises','include_bodyweight'),
  ('exercises','track_reps'),
  ('exercises','default_weight_kg'),
  ('exercises','double_reps'),
  ('exercises','distance_unit'),
  ('exercises','track_time'),
  ('exercises','time_unit'),
  ('exercises','track_resistance'),
  ('exercises','track_speed'),
  ('exercises','speed_unit'),
  ('exercises','track_incline'),
  ('exercises','incline_unit'),
  ('exercises','track_rest'),
  ('exercises','track_calories'),
  ('exercises','track_rpe'),
  ('exercises','track_steps'),
  ('exercises','height_unit'),
  ('exercises','muscles'),
  ('exercises','secondary_muscles'),
  ('exercises','variations'),
  ('exercises','notes'),
  ('exercises','created_at'),
  ('workouts','id'),
  ('workouts','user_id'),
  ('workouts','name'),
  ('workouts','performed_on'),
  ('workouts','session_type'),
  ('workouts','notes'),
  ('workouts','notes_public'),
  ('workouts','calories'),
  ('workouts','duration_sec'),
  ('workouts','created_at'),
  ('workouts','updated_at'),
  ('sets','id'),
  ('sets','user_id'),
  ('sets','performed_on'),
  ('sets','workout_id'),
  ('sets','exercise_id'),
  ('sets','position'),
  ('sets','reps'),
  ('sets','weight_kg'),
  ('sets','bodyweight_kg'),
  ('sets','distance_km'),
  ('sets','duration_sec'),
  ('sets','resistance'),
  ('sets','speed_ms'),
  ('sets','incline_pct'),
  ('sets','rest_sec'),
  ('sets','calories'),
  ('sets','rpe'),
  ('sets','steps'),
  ('sets','height_m'),
  ('sets','circuit_id'),
  ('sets','circuit_rounds'),
  ('sets','circuit_name'),
  ('sets','variation'),
  ('sets','notes'),
  ('sets','notes_public'),
  ('user_field_options','id'),
  ('user_field_options','user_id'),
  ('user_field_options','kind'),
  ('user_field_options','parent_id'),
  ('user_field_options','key'),
  ('user_field_options','label'),
  ('user_field_options','position'),
  ('user_field_options','created_at'),
  ('follows','id'),
  ('follows','follower_id'),
  ('follows','followee_id'),
  ('follows','created_at'),
  ('session_guests','id'),
  ('session_guests','user_id'),
  ('session_guests','workout_id'),
  ('session_guests','guest_profile_id'),
  ('session_guests','guest_name'),
  ('session_guests','position'),
  ('session_guests','created_at'),
  ('templates','id'),
  ('templates','user_id'),
  ('templates','name'),
  ('templates','session_type'),
  ('templates','notes'),
  ('templates','notes_public'),
  ('templates','created_at'),
  ('templates','updated_at'),
  ('template_sets','id'),
  ('template_sets','template_id'),
  ('template_sets','user_id'),
  ('template_sets','exercise_id'),
  ('template_sets','position'),
  ('template_sets','reps'),
  ('template_sets','weight_kg'),
  ('template_sets','distance_km'),
  ('template_sets','duration_sec'),
  ('template_sets','resistance'),
  ('template_sets','speed_ms'),
  ('template_sets','incline_pct'),
  ('template_sets','rest_sec'),
  ('template_sets','calories'),
  ('template_sets','rpe'),
  ('template_sets','steps'),
  ('template_sets','height_m'),
  ('template_sets','circuit_id'),
  ('template_sets','circuit_rounds'),
  ('template_sets','circuit_name'),
  ('template_sets','variation'),
  ('template_sets','notes'),
  ('template_sets','notes_public')
)
select e.tbl, e.col
from expected e
left join information_schema.columns c
  on c.table_schema = 'public' and c.table_name = e.tbl and c.column_name = e.col
where c.column_name is null
order by e.tbl, e.col;

-- Also worth checking: a self-follow row. `user_workouts`/`user_sets` project
-- SELECT * while `followee_workouts`/`followee_sets` project a masked column
-- list. If a row in `follows` has follower_id = followee_id, your own rows
-- arrive through BOTH buckets and the masked copy can overwrite your own
-- notes/notes_public locally. Expected: zero rows.
select follower_id from follows where follower_id = followee_id;
